services:
  init_db:
    image: giraffejump/giraffe_core:${VERSION}
    container_name: giraffe_init_db
    command: upgrade_db
    deploy:
      mode: replicated-job
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/giraffejump/data
    networks:
      - net
